
# @author madebycm (2025-01-26)

services:
  sbox:
    build: .
    container_name: persistent-sbox
    stdin_open: true
    tty: true
    volumes:
      - ${PROJECT_PATH:-./projects/default}:/project
      - sbox-data:/data
      - sbox-usr:/usr
      - sbox-var:/var
      - sbox-etc:/etc
      - sbox-opt:/opt
      - sbox-home:/home
      - sbox-root:/root
    command: /bin/bash

volumes:
  sbox-data:
  sbox-usr:
  sbox-var:
  sbox-etc:
  sbox-opt:
  sbox-home:
  sbox-root: