# @author madebycm (2025-01-26)
version: '3.8'

services:
  sandbox-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: sandbox-base:latest
    command: echo "Base image built successfully"